WIP
VideoCentrix/nx_open pull request #1
Opened 2024-07-12 10:44 UTC by elrinor

2024-07-12 19:15 UTC, kdsx commented on vms/client/nx_vms_client_desktop/src/utils/media/audio_player.cpp
> +    m_renderer = new QnAudioStreamDisplay( AUDIO_BUF_SIZE, AUDIO_BUF_SIZE / 2, /*withAnalyzer=*/false );
```suggestion
    m_renderer = new QnAudioStreamDisplay(AUDIO_BUF_SIZE, AUDIO_BUF_SIZE / 2, /*withAnalyzer*/ false);
```

2024-07-12 19:15 UTC, kdsx commented on vms/client/nx_vms_client_desktop/src/ui/graphics/items/resource/voice_spectrum_painter.h
> +struct QnVoiceSpectrumPainterOptions {
Please put everything to `mx::vms::client::desktop` namespace and name the classes without the `Qn` prefix.

2024-07-12 19:15 UTC, kdsx commented on vms/client/nx_vms_client_desktop/src/ui/graphics/items/resource/voice_spectrum_painter.h
> +        m_options = options;
It seems like this could be just a public field `options`.

2024-07-12 19:15 UTC, kdsx commented on vms/client/nx_vms_client_desktop/src/ui/graphics/items/resource/voice_spectrum_painter.h
> +    QColor visualizerColor;
It looks like you can rename it to `color` as there are no other colors.

2024-07-12 19:15 UTC, kdsx commented on vms/client/nx_vms_client_desktop/src/ui/graphics/items/resource/voice_spectrum_painter.cpp
> +    NX_ASSERT(isValidIndex, "Invalid timeStep value");
I see it is available indirectly, but please include `nx/utils/log/assert.h`

2024-09-17 10:58 UTC, Grey-DeMonstr requested changes

2024-09-17 10:58 UTC, Grey-DeMonstr commented on .gitignore
> +/cmake-build-*/
I'm not very used to github, but this warning sign looks like the EOF newline was removed

2024-09-17 10:58 UTC, Grey-DeMonstr commented on cmake/compiler_options.cmake
> +            -Wno-enum-constexpr-conversion
There should be at least a motivating comment.

2024-09-17 10:58 UTC, Grey-DeMonstr commented on vms/client/nx_vms_client_core/external_resources/skin/basic_colors.json
> +                "active": "#4caf50",
I will consult how to write this in 6.1-compatible way where this file is removed.

2024-09-17 10:58 UTC, Grey-DeMonstr commented on vms/client/nx_vms_client_core/src/utils/media/voice_spectrum_analyzer.cpp
> +        return;
By our coding style, when `if` is multiline, body must be in braces.

2024-09-17 10:58 UTC, Grey-DeMonstr commented on vms/client/nx_vms_client_core/src/utils/media/voice_spectrum_analyzer.cpp
> +void QnVoiceSpectrumAnalyzer::processData(const nx::media::audio::Format& format, const void* sampleData, int sampleBytes) {
Braces on the next line, and 100 symbols limit.
```suggestion
void QnVoiceSpectrumAnalyzer::processData(
    const nx::media::audio::Format& format,
    const void* sampleData,
    int sampleBytes)
{
```

2024-09-17 10:58 UTC, Grey-DeMonstr commented on vms/client/nx_vms_client_desktop/src/camera/audio_stream_display.cpp
> +#include "utils/media/voice_spectrum_analyzer.h"
Only local includes (same or near folder) should be in `"`, otherwise `<>` must be used.

2024-09-17 10:58 UTC, Grey-DeMonstr commented on vms/client/nx_vms_client_desktop/src/camera/audio_stream_display.cpp
> +        // TODO(elric): for now we only support 16-bit and 32-bit signed ints here, is this OK?
```suggestion
        //TODO: #afokin For now we only support 16-bit and 32-bit signed ints here, is this OK?
```

2024-09-17 10:58 UTC, Grey-DeMonstr commented on vms/client/nx_vms_client_desktop/src/camera/audio_stream_display.cpp
> +bool QnAudioStreamDisplay::isDecodeOnly() const {
```suggestion
bool QnAudioStreamDisplay::isDecodeOnly() const
{
```

2024-09-17 10:58 UTC, Grey-DeMonstr commented on vms/client/nx_vms_client_desktop/src/client/client_globals.h
> +        MutedRole, /**< Role for `MuteAction` paramater. (bool) */
```suggestion
        MutedRole, /**< Role for `MuteAction` parameter (bool). */
```

2024-09-17 11:04 UTC, Grey-DeMonstr commented on vms/client/nx_vms_client_desktop/src/nx/vms/client/desktop/ui/graphics/items/overlays/audio_spectrum_overlay_widget.cpp
> +class AudioSpectrumOverlayWidget::Private
We generally recommend `Private` classes to be simple structs. In this case it can ever has no methods at all.
```
struct AudioSpectrumOverlayWidget::Private
{
    AudioSpectrumOverlayWidget* const q; //< Not sure it sis needed.
    QnResourceDisplayPtr const display;
    AudioSpectrumWidget* const widget;
}
...
AudioSpectrumOverlayWidget::AudioSpectrumOverlayWidget(
    QnResourceDisplayPtr display,
    QGraphicsWidget* parent)
    :
    base_type(parent),
    d(new Private{
        .q = this,
        .display = display,
        .widget = new AudioSpectrumWidget(display, this)
    })
```

2024-09-17 12:36 UTC, Grey-DeMonstr requested changes

2024-09-17 12:36 UTC, Grey-DeMonstr commented on vms/client/nx_vms_client_desktop/src/ui/graphics/items/resource/media_resource_widget.cpp
> +bool QnMediaResourceWidget::isMuted() const {
```suggestion
bool QnMediaResourceWidget::isMuted() const
{
```

2024-09-17 12:36 UTC, Grey-DeMonstr commented on vms/client/nx_vms_client_desktop/src/ui/graphics/items/resource/media_resource_widget.cpp
> +void QnMediaResourceWidget::setMuted(bool muted) {
```suggestion
void QnMediaResourceWidget::setMuted(bool muted)
{
```

2024-09-17 12:36 UTC, Grey-DeMonstr commented on vms/client/nx_vms_client_desktop/src/ui/graphics/items/resource/media_resource_widget.cpp
> +void QnMediaResourceWidget::updateAudioPlaybackState() {
```suggestion
void QnMediaResourceWidget::updateAudioPlaybackState()
{
```

2024-09-17 12:36 UTC, Grey-DeMonstr commented on vms/client/nx_vms_client_desktop/src/ui/graphics/items/resource/voice_spectrum_painter.h
> +
```suggestion
} // namespace nx::vms::client::desktop

```

2024-09-17 12:36 UTC, Grey-DeMonstr commented on vms/client/nx_vms_client_desktop/src/ui/workbench/handlers/workbench_action_handler.cpp
> +void ActionHandler::at_muteAction_triggered() {
```suggestion
void ActionHandler::at_muteAction_triggered()
{
```

2024-09-17 12:36 UTC, Grey-DeMonstr commented on vms/client/nx_vms_client_desktop/src/ui/workbench/handlers/workbench_action_handler.cpp
> +    for (QnResourceWidget* widget : parameters.widgets())
```suggestion
    for (QnResourceWidget* widget: parameters.widgets())
```

2024-09-17 12:36 UTC, Grey-DeMonstr commented on vms/client/nx_vms_client_desktop/src/ui/workbench/handlers/workbench_action_handler.cpp
> +        if (widget->visibleButtons() & Qn::MuteButton)
```suggestion
        if (widget->visibleButtons().testFlag(Qn::MuteButton))
```

2024-09-17 12:36 UTC, Grey-DeMonstr commented on vms/client/nx_vms_client_desktop/src/nx/vms/client/desktop/ui/actions/action_factories.cpp
> +    for (const QnResourceWidget* widget : parameters.widgets())
```suggestion
    for (const QnResourceWidget* widget: parameters.widgets())
```

2024-09-17 12:36 UTC, Grey-DeMonstr commented on vms/client/nx_vms_client_desktop/src/ui/workbench/handlers/workbench_action_handler.cpp
> +            // This action is just pressing buttons. All logic is in button handlers.
This looks weird for me. Imho all logic should be in the widget methods (`void mute()` and `void unmute()`), and buttons should be checked there. Not vise versa.

2024-09-17 12:36 UTC, Grey-DeMonstr commented on vms/client/nx_vms_client_desktop/src/nx/vms/client/desktop/ui/actions/action_conditions.cpp
> +    // All logic is in the visibility of mute / unmute button. So this is what we check here.
I would suggest widget to have `bool hasAudio() const` or may be `bool canBeMuted() const` methods, which will be checked here - and in the `calculateButtonsVisibility()`. Using button state here is a side effect, which creates a technical debt (e.g. we faced such issues when tried to implement alternative media widgets on QML scene).

2024-09-17 12:36 UTC, Grey-DeMonstr commented on vms/client/nx_vms_client_desktop/src/nx/vms/client/desktop/ui/actions/action_factories.cpp
> +        if (widget->visibleButtons() & Qn::MuteButton)
Please use the widget methods here also

2024-09-17 12:36 UTC, Grey-DeMonstr commented on vms/client/nx_vms_client_desktop/src/ui/workbench/workbench_display.cpp
> +            existingItemIds.insert(itemId);
```suggestion
    for (const auto& otherLayout: resourcePool()->getResources<QnLayoutResource>())
    {
        for (const auto& itemId: otherLayout->getItems().keys())
            existingItemIds.insert(itemId);
    }
```

2024-09-17 12:36 UTC, Grey-DeMonstr commented on vms/client/nx_vms_client_desktop/src/ui/workbench/workbench_navigator.cpp
> +        // This is a hack. We need to call QnCamDisplay::playAudio b/c QnCamDisplay ignores playAudio calls when paused
`hack` is a forbidden word in the opensource code. Use `ad-hoc solution` instead :)

2024-09-17 12:36 UTC, Grey-DeMonstr commented on vms/client/nx_vms_client_desktop/src/utils/media/audio_player.cpp
> +    m_renderer = new QnAudioStreamDisplay(AUDIO_BUF_SIZE, AUDIO_BUF_SIZE / 2, /*withAnalyzer*/ false, /*decodeOnly*/ false);
Line is longer than 100 symbols
```suggestion
    m_renderer = new QnAudioStreamDisplay(
        AUDIO_BUF_SIZE,
        AUDIO_BUF_SIZE / 2,
        /*withAnalyzer*/ false,
        /*decodeOnly*/ false);
```

2024-09-17 12:47 UTC, elrinor commented on vms/client/nx_vms_client_desktop/src/ui/workbench/handlers/workbench_action_handler.cpp
> +        if (widget->visibleButtons() & Qn::MuteButton)
It's an `int` =(

2024-09-17 12:51 UTC, elrinor commented on vms/client/nx_vms_client_desktop/src/nx/vms/client/desktop/ui/actions/action_conditions.cpp
> +    // All logic is in the visibility of mute / unmute button. So this is what we check here.
Agreed, will change how state is managed, thnx

2024-09-17 14:02 UTC, vasilenkoroman commented on vms/client/nx_vms_client_desktop/src/camera/cam_display.h
> +    bool analyzesAudio() const;
I think there are too many bool setters:
- mute/unmute
- audiDecodeOnly
- analyzeAudio
So, can we redesign it to some `enum class AudioDecodePolicy`? If there are to much combination then it could be some QFlag instead of enum.

2024-09-17 14:04 UTC, vasilenkoroman commented on vms/client/nx_vms_client_desktop/src/camera/audio_stream_display.cpp
> +        // TODO: #afokin for now we only support 16-bit and 32-bit signed ints here, is this OK?
Sometimes there is float32 format. I suggest check next codecs:
- mp3
- aac
If there is no issue with float32 you can avoid it. Also there is helper functions to convert it to int32.

2024-09-17 14:08 UTC, vasilenkoroman commented on vms/client/nx_vms_client_desktop/src/camera/cam_display.h
> +    void setAudioDecodeOnly(bool audioDecodeOnly);
Can you add comment why this mode became required?

2024-09-17 16:27 UTC, elrinor commented on vms/client/nx_vms_client_desktop/src/camera/cam_display.h
> +    bool analyzesAudio() const;
Will do flags for analyzes / doesn't analyze & plays back / only decodes.

2024-09-17 19:32 UTC, elrinor commented on vms/client/nx_vms_client_desktop/src/camera/cam_display.h
> +    bool analyzesAudio() const;
Added `enum class AudioDecodeMode`, can rename to -`Policy` if needed.

2024-09-17 19:46 UTC, elrinor commented on vms/client/nx_vms_client_desktop/src/camera/audio_stream_display.cpp
> +        // TODO: #afokin for now we only support 16-bit and 32-bit signed ints here, is this OK?
AAC works, not sure how to test if MP3 works, but I'm not aware of fp32 MP3s, so should work too.

Seriously though, I'll need specific instructions here X). Should I implement it, or should I not.

2024-09-17 19:48 UTC, elrinor commented on vms/client/nx_vms_client_desktop/src/camera/cam_display.h
> +    void setAudioDecodeOnly(bool audioDecodeOnly);
Added docs for `enum class AudioDecodeMode`, should be self-explanatory.

2024-09-18 11:14 UTC, elrinor commented on vms/client/nx_vms_client_desktop/src/ui/workbench/handlers/workbench_action_handler.cpp
> +        if (widget->visibleButtons() & Qn::MuteButton)
Also, no longer relevant, dropped this code.

2024-09-18 14:18 UTC, Grey-DeMonstr commented on vms/client/nx_vms_client_desktop/src/nx/vms/client/desktop/ui/actions/action_conditions.cpp
> +        QnMediaResourceWidget* mediaWidget = dynamic_cast<QnMediaResourceWidget*>(widget);
```suggestion
    for (QnResourceWidget* widget: parameters.widgets())
    {
        auto mediaWidget = qobject_cast<QnMediaResourceWidget*>(widget);
```

2024-09-18 14:18 UTC, Grey-DeMonstr commented on vms/client/nx_vms_client_desktop/src/nx/vms/client/desktop/camera/audio_decode_mode.h
> +enum class AudioDecodeMode {
```suggestion
enum class AudioDecodeMode
{
```

2024-09-18 14:18 UTC, Grey-DeMonstr commented on vms/client/nx_vms_client_desktop/src/nx/vms/client/desktop/ui/graphics/items/overlays/audio_spectrum_overlay_widget.cpp
> +#include "ui/common/palette.h"
Those two includes must be in the `<>`

2024-09-18 14:18 UTC, Grey-DeMonstr commented on vms/client/nx_vms_client_desktop/src/nx/vms/client/desktop/ui/graphics/items/overlays/audio_spectrum_overlay_widget.h
> +    const QScopedPointer<Private> d;
We recommend using `nx::utils::ImplPtr<Private> d;` or `std::unique_ptr<Private>` cause `QScopedPointer` is marked as deprecated, but this is optional.

2024-09-18 14:18 UTC, Grey-DeMonstr commented on vms/client/nx_vms_client_desktop/src/ui/graphics/items/resource/voice_spectrum_painter.h
> +struct VoiceSpectrumPainterOptions {
```suggestion
struct VoiceSpectrumPainterOptions
{
```

2024-09-18 14:18 UTC, Grey-DeMonstr commented on vms/client/nx_vms_client_desktop/src/ui/graphics/items/resource/voice_spectrum_painter.h
> +class VoiceSpectrumPainter {
```suggestion
class VoiceSpectrumPainter
{
```

2024-09-18 14:18 UTC, Grey-DeMonstr commented on vms/client/nx_vms_client_desktop/src/ui/workbench/handlers/workbench_action_handler.cpp
> +        QnMediaResourceWidget* mediaWidget = dynamic_cast<QnMediaResourceWidget*>(widget);
```suggestion
        auto mediaWidget = qobject_cast<QnMediaResourceWidget*>(widget);
```

2024-09-18 14:35 UTC, vasilenkoroman commented on vms/client/nx_vms_client_desktop/src/camera/audio_stream_display.cpp
> +        // TODO: #afokin for now we only support 16-bit and 32-bit signed ints here, is this OK?
I think it is better to support to be on the safe side. There are lines:
```    if (format.sampleType == nx::media::audio::Format::SampleType::floatingPoint)
    {
        format.sampleType = nx::media::audio::Format::SampleType::signedInt;
        if (nx::audio::Sound::isFormatSupported(format))
```
You can declare format FloatingPoint as unsupported to force float32->int conversion. It is already exists in QnAudioStreamDisplay

2024-09-23 20:52 UTC, elrinor commented
Discarding

2024-09-23 20:52 UTC, closed without merging